spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 715826611914-ucqkfg6qjh371jagsqlhbdev5aoso9cu.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email, birthday 


